### ISSUE TITLE
Issue with Wagons

### ISSUE THREAD

**Issue by Equinox76** [bdew-wurm/movemod#2]
Hello,

Mod is great and works well with default wagons. Doesn't seem to run at all with the extra kingdom wagons (black legion, etc...). Could these be added?

**Comment by bdew** [comment]
I can't add support for items from other mods.

This mod creates a ModVehicleBehaviour instance for vanilla items which applies the changes.

Modded items already have their own ModVehicleBehaviour created by the mod that adds them, so any configuration should happen in the mod that adds the item.
